### ISSUE TITLE
argument 1 must be str, not bool

### ISSUE THREAD

**Issue by robkam** [saveweb/dokuwiki-scraper#1]
`$ dokuWikiScraper.exe --content --media wiki.midibox.org`

...snip..,.
```
    Revision 1219908244 of [[ssm2044_pcb_bulk_order]] saved.
    meta change saved: {'id': '1219908244', 'user': '', 'sum': 'external edit', 'date': '2008/08/28 07:24'}
    meta change saved: {'id': '1232321122', 'user': 'seppoman', 'sum': '', 'date': '2009/01/18 23:25'}
    meta change saved: {'id': '1233605464', 'user': 'seppoman', 'sum': '', 'date': '2009/02/02 20:11'}
    meta change saved: {'id': '1233609033', 'user': False, 'sum': '', 'date': ''}
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python\Scripts\dokuWikiScraper.exe\__main__.py", line 7, in <module>
  File "C:\Python\Lib\site-packages\dokuWikiScraper\__init__.py", line 4, in main
    dump()
  File "C:\Python\Lib\site-packages\dokuWikiScraper\dump\dokuDumper.py", line 70, in dump
    dumpContent(url=dokuUrl, dumpDir=dumpDir, session=session, skipTo=skipTo)
  File "C:\Python\Lib\site-packages\dokuWikiScraper\dump\content\__init__.py", line 109, in dumpContent
    socket.inet_aton(rev['user'])
TypeError: inet_aton() argument 1 must be str, not bool
```

**Comment by yzqzss** [comment]
How about now?

**Comment by robkam** [comment]
It ran to completion :-)
